name: Deploy Crawler

on:
  push:
    branches:
      - main
    paths:
      - 'crawler.py'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: 165.227.145.80
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/whoknows-crawler
            git pull
            docker-compose rm -f crawler
            docker-compose up -d
